/**
 * Типы ответов API. Единственное описание живёт на сервере (server/src/apiTypes.ts):
 * сервер аннотирует им то, что отдаёт, а здесь они лишь реэкспортируются — чисто типовой
 * импорт, в бандл ничего не попадает. Не дублируйте интерфейсы в этом файле.
 */
export type {
  AnnouncementItem,
  AnnouncePhase,
  AnnounceProgress,
  AnnounceResponse,
  AudioCatalogTrack,
  AudioChannel,
  AudioClip,
  DisplayAudio,
  AnnouncementRecipient,
  Attention,
  Pulse,
  PulseSample,
  ProvisionItem,
  ProvisionQr,
  ProvisionsResponse,
  AuditResponse,
  BulkPreview,
  ChangeRow,
  CharacterSnapshot,
  DisplayGroup,
  DisplayItem,
  DisplayPreview,
  DisplayPushResponse,
  DisplayPushPhase,
  DisplayPushResult,
  DisplayPushState,
  DisplaySecretResponse,
  DisplayStatus,
  Economy,
  EventsResponse,
  FactionRow,
  Meta,
  NodeDetail,
  NodeSummary,
  Overview,
  PlayerListItem,
  SlotRegistryItem,
  TargetSelector,
  Transfer,
  WatchItem,
} from "../../../server/src/apiTypes";
